### ISSUE TITLE
Problem about guide and routing

### ISSUE THREAD

**Issue by ghost** [cuhk-eda/dr-cu#3]
We meet some strange questions while using Dr. CU.
Hope we can get the answer from you kindly^^
Here is the question : 
while we give guides to Dr. CU, Dr. CU ignored our guide and routed a truck tree... what situations may cause this to happen?

here is an example...
the figure is ispd18_test3,
the colored line is our guide and the light black line is the detailed routing from Dr. CU
it seems like a trunk tree and ignored our guide
![problem](https://user-images.githubusercontent.com/49803719/70550917-7ee01f00-1bb1-11ea-896d-3c496c02908f.png)

and here is the log file 
the log file did not appear any related error or warning
![problem 2](https://user-images.githubusercontent.com/49803719/70550916-7e478880-1bb1-11ea-80e6-2f08db5545e1.PNG)

**Comment by Rholais** [comment]
The router failed to connect the net and had to avoid open by some brute force using [single-truck tree](https://github.com/cuhk-eda/dr-cu/blob/master/src/multi_net/Router.cpp#L254).
Could you check if the guides of every net are connected?
In case `ispd18_test4`, the IO pins are placed on `Metal7` and `Metal8`, which potentially causes disconnected guides.

**Comment by Rholais** [comment]
@creamycreamcream I have updated the code to report nets with detached pins.

**Comment by ghost** [comment]
@Rholais 
we have try to compile your new source code but ended up some errors....
it is fine to compile with the old source code though
is there anything i need to install or how can i solve this problem?
![image](https://user-images.githubusercontent.com/49803719/71360732-b5636400-25cb-11ea-8f22-c1a12a03cc09.png)

**Comment by Rholais** [comment]
Can you successfully compile commit [24660aa](https://github.com/cuhk-eda/dr-cu/commit/24660aa2d266f7b0b73988f4af4dad60ccfbd0c8) or [bac7464](https://github.com/cuhk-eda/dr-cu/commit/bac7464ae8369636e6706f24d9109b4550b5aee5)?
You may try to remove the `-static` flag in [Line 84 of src/CMakeLists.txt](https://github.com/cuhk-eda/dr-cu/blob/master/src/CMakeLists.txt#L84).

**Comment by ghost** [comment]
i removed the -static flag but also meet the same problem
and i have tried to changed the source code back it's still the same problem too

is it work fine while compiling on your server?

**Comment by Rholais** [comment]
Yes, it compiles fine on our server.
Have you try both commits [24660aa](https://github.com/cuhk-eda/dr-cu/commit/24660aa2d266f7b0b73988f4af4dad60ccfbd0c8) and [bac7464](https://github.com/cuhk-eda/dr-cu/commit/bac7464ae8369636e6706f24d9109b4550b5aee5)?

> it is fine to compile with the old source code though

Which version of old source code did you try?

You may try to comment out [Line 36 of src/CMakeLists.txt](https://github.com/cuhk-eda/dr-cu/blob/master/src/CMakeLists.txt#L36).

**Comment by ghost** [comment]
it works when i comment out Line 36 of src/CMakeLists.txt.
will the performance be difference with out this line?
or any other command can substitute this line?

**Comment by Rholais** [comment]
[Line 36](https://github.com/cuhk-eda/dr-cu/blob/master/src/CMakeLists.txt#L36) is about the linking of [Boost](https://www.boost.org).
Different versions and compilation options of Boost may affect runtime performance and result.

Do the nets routed by single-trunk trees have detached pins?

**Comment by ghost** [comment]
ok, i will only use new version for finding detached pins^^

yes, the problem have solved by linking detached pins together

i have another question.....
i use new version of DRCU to check our guide and find out there is no detached pins but there is an warning line appear

![image](https://user-images.githubusercontent.com/49803719/71457767-8ec74800-27da-11ea-912d-4790f0e159dd.png)

what situation may cause this problem
and also i would like to know the what situation may cause error line too 

![image](https://user-images.githubusercontent.com/49803719/71457801-b3bbbb00-27da-11ea-9b74-f9d07919d7cf.png)

thanks for your kindly reply

**Comment by Rholais** [comment]
As you can see from the error message, the guides of these four nets are detached.
Then Dr. CU tries to connect these guides by expansion.
Three of them succeeded after several iterations.
The last one `net35341` failed.
Please make sure that the guides of a net are connected.

**Comment by Rholais** [comment]
@creamycreamcream I will close the issue if there is no other problem regarding detached pins.
